version: "3.1"

services:
    mariadb:
        image: "mariadb:10.5"
        restart: 'always'
        ports: 
            - "3307:3307"
        environment: 
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ormnode
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        networks:
            - app-network

    adminer:
        image: adminer
        links:
            - mariadb:test
        restart: always
        ports:
            - '8081:8081'
        environment:
            MYSQL_ROOT_PASSWORD: test
            MYSQL_DATABASE: test
            MYSQL_USER: test
            MYSQL_PASSWORD: test
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
